### ISSUE TITLE
Lack of certificate and key content

### ISSUE THREAD

**Issue by gitnetofr** [Radware/radware-ansible#105]
## Bug Report 

**##### CUSTOMER**
Orange France

**##### SEVERITY**
Critical

**##### SUMMARY**
When using the gather fact module to retrieve certificates and keys, we don't have the contents 
otherwise we don't have a module to retrieve the certificates request nor a module to configure it.

**##### STEPS TO REPRODUCE**
This is the code we use it to retrieve the configuration of the certificates end keys:
```
    - name: alteon device configuration
      alteon_device_facts:
        provider: "{{ oalteonprimoconfConnectionParams }}"
        gather_facts:
           - ssl_cert
           - ssl_key
      register: facts
```

- The collection we are using is 0.0.9
- The version of radware is 32.2.8.0

##### EXPECTED RESULTS
What we expect to have as a result is all the configuration of certificats, keys and requests with their content.
```
"ssl_cert": [
{
               "certificate_expiry": "******************",
               "certificate_type": "*************",
                "common_name": "***********",
                "description": "",
                "ec_curve_name": "**********",
                "hash_algorithm": "*****",
                "index": "*************",
                "intermediate_ca_name": "",
                "intermediate_ca_type": "",
                "key_size": ****,
                "key_type": "***",
                "serial_number": "**********************",
                "subject_alternative_name": "IP:*******",
                "subject_country": "**",
                "subject_email_address": "********",
                "subject_locality": "******",
                "subject_organization": "********",
                "subject_organization_unit_name": "***",
                "subject_state_province": "***",
                "validation_period": *
                **"content": " ***********************************************************************************"**

}]
```
```
"ssl_key": [
        {
             "description": "",
               "index": "***",
               "key_size": ***,
               **"content": " ***********************************************************************************"**
         }]
```

##### ACTUAL RESULTS
This is an example to a retrived certificate and key fact with the gather fact module and as we can see we don't have the content  parameter:
```
ssl_cert: [
{
               "certificate_expiry": "******************",
               "certificate_type": "*************",
                "common_name": "***********",
                "description": "",
                "ec_curve_name": "**********",
                "hash_algorithm": "*****",
                "index": "*************",
                "intermediate_ca_name": "",
                "intermediate_ca_type": "",
                "key_size": ****,
                "key_type": "***",
                "serial_number": "**********************",
                "subject_alternative_name": "IP:*******",
                "subject_country": "**",
                "subject_email_address": "********",
                "subject_locality": "******",
                "subject_organization": "********",
                "subject_organization_unit_name": "***",
                "subject_state_province": "***",
                "validation_period": *
} ]
```
```
"ssl_key": [
        {
             "description": "",
               "index": "***",
               "key_size": ***
         }]
```

**Comment by onurbrc** [comment]
Hi, would be possible to choose when read services certificate context?
Ex.:   # Yes
````yaml
    - name: Facts
      alteon_device_facts:
        gather_facts:
           - ssl_cert
           - ssl_key
      register: facts
````

Ex.:   # No
````yaml
    - name: Facts
      alteon_device_facts:
        gather_facts:
           - !ssl_cert
           - !ssl_key
      register: facts
````
