### ISSUE TITLE
No module for request certificate recuperation/get

### ISSUE THREAD

**Issue by gitnetofr** [Radware/radware-ansible#106]
**This feature request is related to a problem:** _(It's critical feature for our work)_
When I use the gather fact module, there is no possibility to display the configuration of CSR (certificates request) and there is no module to configure it too.

**The solution I'd like**
I would like to have the possibility to get the CSR configuration and configure it on another machine
```
    - name: alteon device configuration
      alteon_device_facts:
        provider: "{{ oalteonprimoconfConnectionParams }}"
        gather_facts:
           - ssl_csr
      register: facts

```
**The configuration I want to retrieve is:**
```
/c/slb/ssl/certs/request *****************
/c/slb/ssl/certs/import request "****************" text
-----BEGIN CERTIFICATE REQUEST-----
******************************************************
-----END CERTIFICATE REQUEST-----
```
