### ISSUE TITLE
No module for Script Health Check recuperation/get

### ISSUE THREAD

**Issue by gitnetofr** [Radware/radware-ansible#107]
**This feature request is related to a problem:** 
when I use the gather fact module, there is no possibility to display the configuration of script health check and there is no module to configure it too.

**The solution I'd like**
I would like to have the possibility to get the Script Health check configuration and configure it on another machine
```
    - name: alteon device configuration
      alteon_device_facts:
        provider: "{{ oalteonprimoconfConnectionParams }}"
        gather_facts:
           - script_hc
      register: facts

```
**The configuration I want to retrieve is:**
```
/c/slb/advhc/health script1 SCRIPT
/c/slb/advhc/health script1 SCRIPT/script
        open "80,tcp"
        send "GET / / HTTP/2.0\\r\\nHOST: \\r\\n\\r\\n"
        expect "HTTP"
        close
```
