### ISSUE TITLE
SSL POLICY Configuration Module

### ISSUE THREAD

**Issue by gitnetofr** [Radware/radware-ansible#109]
##### CUSTOMER
Orange France

##### SEVERITY
Critical

##### SUMMARY
The None value of Usage: intermca [cert|group|none] <certificate or group name> that is not taken into account in the ssl policy configuration module

##### STEPS TO REPRODUCE

```
 - name: alteon ssl policy configuration command
      radware.radware_modules.alteon_config_ssl_policy:
        provider: "{{ oalteonProviderprimoconfConnectionParams }}"
        state: present
        parameters:
          index: "{{ current_ssl_policy_obj.obj.index }}"
          state: "{{ current_ssl_policy_obj.obj.state  }}"
          fe_intermediate_ca_chain_type: none
```

##### EXPECTED RESULTS
fe_intermediate_ca_chain_type in ths ssl policy configuration accept the none value

##### ACTUAL RESULTS
fe_intermediate_ca_chain_type in ths ssl policy configuration didn't accept the none value

`    "msg": "value of fe_intermediate_ca_chain_type must be one of: group, cert, got:  found in parameters"`
