### ISSUE TITLE
Bug on PIP6 modules --check mode

### ISSUE THREAD

**Issue by gitnetofr** [Radware/radware-ansible#22]
##### SEVERITY
Low

##### SUMMARY

Pip6 Ansible result in --check mode is always on "changed" even if the configuration is already done.

##### ENVIRONMENT
```
ansible 2.9.6
python version      = 3.7.3
Ansible Collection  = radware.radware_modules:0.0.3
Software version: 32.4.1.10
Distribution: Application Switch VA
```

##### STEPS TO REPRODUCE

Alteon configuration before executing playbook
```
/c/slb/pip/add6 1000:0:0:0:0:0:0:1 333
```

Playbook executed with --check mode
```
  alteon_config_slb_pip6:
    state: present
    parameters:
      base_type: "vlan"
      vlans: "333"
      pip6_addr: "1000::1"
    provider: "{{ providerParams }}"
  delegate_to: localhost

```

##### EXPECTED RESULTS

```
alteon : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
##### ACTUAL RESULTS

```
alteon : ok=0    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
