### ISSUE TITLE
vlan def 0 not accepted

### ISSUE THREAD

**Issue by gitnetofr** [Radware/radware-ansible#23]
##### SEVERITY

Low
##### SUMMARY

Not possible to remove one vlan from all interfaces because "0" value is not accepted
##### ENVIRONMENT
```
ansible 2.9.6
python version      = 3.7.3
Ansible Collection  = radware.radware_modules:0.0.3
Software version: 32.4.1.10
Distribution: Application Switch VA
```
##### STEPS TO REPRODUCE

```
  alteon_config_l2_vlan:
    state: present
    parameters:
      index: 1
      name: "Default VLAN"
      source_mac_learning: enabled
      ports: [0]
      state: "disabled"
    provider: "{{ providerParams }}"
  delegate_to: localhost
```
##### EXPECTED RESULTS

```
/c/l2/vlan 1
        dis
        learn ena
        def 0
```
##### ACTUAL RESULTS

"msg": "\nRest Request Error:\nStatus: 406\nReason: None\nurl= https://1.1.1.1:443/config/VlanNewCfgTable/1\nmethod= PUT\nbody= {\n\"AddPort\":\"0\",\n}\nDetails: {\n\t \"status\":\"err\",\n\t \"testErr\":\"**Input 0 is out of range[1-3]**.\",\n\t \"mibName\": \"VlanNewCfgTable,AddPort\"\n}.\nAlteon"
