### ISSUE TITLE
HA mode module create HA switch config

### ISSUE THREAD

**Issue by gitnetofr** [Radware/radware-ansible#27]
##### SEVERITY

Low
##### SUMMARY

HA module "alteon_config_high_availability" execution creates HA switch configuration not desired.
If the playbook is executed two times, the second time the ha switch config is deleted.

##### ENVIRONMENT
```
ansible 2.9.6
python version      = 3.7.3
Ansible Collection  = radware.radware_modules:0.0.3
Software version: 32.4.1.10
Distribution: Application Switch VA
```
##### STEPS TO REPRODUCE

```
- name: hamode service
  alteon_config_high_availability:
    state: present
    parameters:
      mode: "service"
    provider: "{{ providerParams }}"
  delegate_to: localhost
  register: __output
```

##### EXPECTED RESULTS

```
/c/l3/hamode service
```

##### ACTUAL RESULTS

```
 /c/l3/hamode service

 /c/l3/ha/switch
 /c/l3/ha/switch/trigger/ifs
        add 2
        add 3
```
