### ISSUE TITLE
Error creating local user on 32.6.4.0

### ISSUE THREAD

**Issue by gitnetofr** [Radware/radware-ansible#40]
##### SEVERITY
High

##### SUMMARY

Error while creating local users on VA version 32.6.4 
While it's ok on version =< 32.6.2

##### ENVIRONMENT
```
ansible 2.9.10
python version = 3.7.5 
Ansible Collection  = radware.radware_modules:0.0.6
alteon-sdk==0.6b57
radware-ansible-common-alteon==0.3b35
radware-sdk-common==0.4b32
Software version: 32.6.4.0
Distribution: Application Switch VA
```

##### STEPS TO REPRODUCE

Playbook executed
```
  alteon_config_system_local_user:
    state: present
    parameters:
      index: 4
      user_name: "toto"
      state: "enabled"
      admin_password: "titi"
      user_password: "tata"
      user_role: "user"
    provider: "{{ providerParams }}"
  delegate_to: localhost

```

##### EXPECTED RESULTS

```
 /c/sys/access/user/uid 4
        name "toto"
        pswd "****"
        ena
```
##### ACTUAL RESULTS

```

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/ansible_alteon_config_system_local_user_payload_ng3zd0jd/ansible_alteon_config_system_local_user_payload.zip/ansible_collections/radware/radware_modules/plugins/modules/alteon_config_system_local_user.py", line 237, in main
  File "/tmp/ansible_alteon_config_system_local_user_payload_ng3zd0jd/ansible_alteon_config_system_local_user_payload.zip/ansible_collections/radware/radware_modules/plugins/module_utils/configuration.py", line 166, in exec_module
    raise RadwareModuleError(e)
ansible_collections.radware.radware_modules.plugins.module_utils.common.RadwareModuleError:
Rest Request Error:
Status: 406
Reason: None
url= https://x.x.x.x:443/config/AgAccessUserNewCfgTable/4
method= PUT
body= {
"AdminPswd":"********",
"Pswd":"********",
"ConfPswd":"********",
}
Details: {
         "status":"err",
         "testErr":"Failed to get username.",
         "mibName": "AgAccessUserNewCfgTable,Pswd"
}.


    "msg": "\nRest Request Error:\nStatus: 406\nReason: None\nurl= https://x.x.x.x:443/config/AgAccessUserNewCfgTable/4\nmethod= PUT\nbody= {\n\"AdminPswd\":\"********\",\n\"Pswd\":\"********\",\n\"ConfPswd\":\"********\",\n}\nDetails: {\n\t \"status\":\"err\",\n\t \"testErr\":\"Failed to get username.\",\n\t \"mibName\": \"AgAccessUserNewCfgTable,Pswd\"\n}.\nAlteon"

```
